server {
    listen 80;
    server_name localhost;
    
    # La ruta donde Docker guarda tu aplicación Angular
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # La regla mágica: Intenta buscar el archivo, si no existe, carga index.html
        try_files $uri $uri/ /index.html;
    }
}